#!/usr/bin/env node

/**
 * So, later on we can use some libraries or build tools to make this nicer, 
 * like we'll be able to build the client and server and compile solidity code 
 * and do all the orchestration from the top level directory
 */

const fs = require('fs');
const path = require('path');

const args = process.argv.slice(2);

// Check if any arguments were provided
if (args.length === 0) {
  console.log('Please provide some input!');
  process.exit(1);
}

const modelPath = path.join(__dirname, 'model.js');
const hashPath = path.join(__dirname, 'hash.js');
const enginePath = path.join(__dirname, 'engine.js');

const copyDir = args[0];

const modelCp = path.join(copyDir, 'model.js');
const engineCp = path.join(copyDir, 'engine.js');
const hashCp = path.join(copyDir, 'hash.js');

fs.copyFile(modelPath, modelCp, (err) => {
    if (err) throw err;
});
fs.copyFile(hashPath, hashCp, (err) => {
    if (err) throw err;
});
fs.copyFile(enginePath, engineCp, (err) => {
    if (err) throw err;
});