#!/usr/bin/env node

/**
 * So, later on we can use some libraries or build tools to make this nicer, 
 * like we'll be able to build the client and server and compile solidity code 
 * and do all the orchestration from the top level directory
 */

const fs = require('fs');
const path = require('path');

const args = process.argv.slice(2);

// Check if any arguments were provided
if (args.length === 0) {
  console.log('Please provide some input!');
  process.exit(1);
}

const modelPath = path.join(__dirname, 'model.js');

const copyPath = args[0];

fs.copyFile(modelPath, copyPath, (err) => {
    if (err) throw err;
});